config/routes.rb
Rails.application.routes.draw do
  get 'tags/:tag', to: 'posts#index', as: :tag
  mount Ckeditor::Engine => '/ckeditor'
  resources :posts
  devise_for :admins, :controllers => { registrations: 'registrations' } 
  root 'posts#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :posts, dependent: :destroy
      
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/attachments/:id/:filename',
                    path: ':rails_root/public/ckeditor_assets/attachments/:id/:filename'

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    path: ':rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    styles: { content: '800>', thumb: '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 2.megabytes
  validates_attachment_content_type :data, content_type: /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :admin
  acts_as_taggable
  acts_as_taggable_on :tag_list
  extend FriendlyId
  friendly_id :title, use: :slugged
  
  
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def index
    @admins = Admin.all
  end
  
  def show
    @admin = Admin.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    if params[:tag]
      @posts = Post.tagged_with(params[:tag]).order("created_at desc").paginate(page: params[:page], per_page: 10)
    else
      @posts = Post.all.order("created_at desc").paginate(page: params[:page], per_page: 10)
    end
  end

  def show
    @post = Post.friendly.find(params[:id])
  end
  
  def new
    @post = Post.new
    @admin= current_admin
  end
  
  def edit
    @post = Post.find(params[:id])
  end  

  def create
    @post = Post.new
    @admin = current_admin
    @post.assign_attributes(post_params)
    @post.admin = @admin
   
    if @post.save
      flash[:notice] = "Successfully created post!"
      redirect_to @post
    else
      flash[:alert] = "Error creating new post!"
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    
    if @post.destroy
      flash[:notice] = "Successfully deleted post!"
      redirect_to posts_path
    else
      flash[:alert] = "Error updating post!"
      render :show
    end
  end
  
  def update
    @post = Post.find(params[:id])
    @post.assign_attributes(post_params)
    
    if @post.save
      flash[:notice] = "You post has been updated."
      redirect_to @post
    else
      flash.now[:alert] = "There was an error editing your post."
      render :edit
    end
  end
  
  
  private
  
  def post_params
    params.require(:post).permit(:title, :body, :link, :tag_list, :slug, :admin_id, :admin_ids => [] )
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:admin).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:admin).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Music Blog</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
</head>

<body ng-app="myApp">
  
  <h1>Checkthesebeats.com</h1>
  <hr>
  <ul class="nav nav-tabs">
    <li><%= link_to "Home" %></li>
    <li><%= link_to "Playlists" %></li>
    <li><%= link_to "About" %></li>
    <li><%= link_to "Song Submission" %></li>
    <div class="user-info pull-right">
        <% if admin_signed_in? %>
              <li>Signed in as: <strong><%= current_admin.name %></strong></li>
              <li><%= link_to 'Edit profile', edit_admin_registration_path, :class => 'navbar-link' %></li>
              <li><%= link_to "Sign Out", destroy_admin_session_path, method: :delete, :class => 'navbar-link' %></li>
            </ul>
            <% end %>
          </div>
  </ul>
  <p class="notice"><%= notice %></p>
  <p class="alert"><% alert %></p>

  <%= yield %>

</body>
</html>

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>

    var disqus_shortname = 'checkthesebeats';
    var disqus_identifier = '<%= @post.id %>'
    var disqus_title = '<%= @post.title %>'
    var disqus_url = '<%= url_for([@post, {only_path: false}]) %>';

(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://checkthesebeats.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
    <%= f.input :title, label: 'Song Title', placeholder: 'Title of the song' %>
    <%= f.input :tag_list, label: 'Tags', placeholder: 'Separate by commas' %>
    <%= f.input :link, label: 'Embedded Link', placeholder: 'Copy and Paste embedded link from Soundcloud/Spotifty.' %>
    <%= f.input :body, :as => :ckeditor, input_html: {:ckeditor => {:toolbar => 'FULL'}}, label: 'Song Description', placeholder: 'Write a brief description of the song.' %>
    <%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<h1> Edit post </h1>

<%= render partial: 'form', locals: {post: @post} %>

app/views/posts/index.html.erb
<div class="row">
    <div class="col-md-8", style="margin-left:10px">
        <% if current_admin %>
            <%= link_to "New Post", new_post_path(@post) %>
        <% end %>
        


    <% @posts.each do |post| %>
        <div class="media">
            <h3 class ="media-heading">
                <%= link_to post.title, post %>
            </h3>
             <small>
                 <p>
                Tags: <%= raw post.tag_list.map { |t| link_to t, tag_path(t)}.join(', ') %>
                </p>
            </small>
            <div class="link">
                <%== post.link %>
            </div>
            <small>
                Posted by: <%= post.admin.name %> | <%= post.created_at.strftime(" %B #{post.created_at.day.ordinalize}, %Y") %> 
                <% if current_admin %>
                    <%= link_to "Edit", edit_post_path(post) %>
                <% end %>
            </small>
            <hr>
        <% end %>
</div>
</div>
</div>

<%= will_paginate @posts %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render partial: 'form', locals: {post: @post} %>

    

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

 <%== @post.link %>
 <%= raw(@post.body) %>
 
 <% if current_admin %>
<%= link_to "Edit", edit_post_path(@post) %>
<%= link_to "Delete", @post, method: :delete, data: {confirm: 'Are you sure you want to delete this post?' } %>
<% end %>


<%= link_to "Back", root_path %>

<%= render partial: 'disqus', locals: {post: @post} %>